BEGIN;

CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS report;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE DOMAIN core.status_text AS text
CHECK (VALUE <> '');

COMMIT;
